osx_image: xcode8.3

dist: trusty
sudo: required

language: node_js
node_js: "8"

env:
  - ELECTRON_CACHE=$HOME/.electron USE_HARD_LINKS=false

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
    - $HOME/.electron

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.1.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.1.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
  - yarn add electron-builder@next --dev # force install next version to test electron-builder
  - cd app && yarn && cd ..
  - rm -rf ./app/node_modules/webworker-threads

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run buildosx ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run buildlinux ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
